name: security-scan
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  dependency-vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: OWASP Dependency Check
        run: |
          mvn -q org.owasp:dependency-check-maven:check -Dformat=ALL || true
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dep-check
          path: '**/dependency-check-report.html'